[program:VNC]
command=bash -c 'PASSWORD=$(jq --raw-output .password /data/options.json); if [ "$PASSWORD" = "null" ] || [ -z "$PASSWORD" ]; then x0vncserver -display :0 -SecurityTypes=None; else echo -n "$PASSWORD" |vncpasswd -f > $HOME/.config/tigervnc/passwd && x0vncserver -PasswordFile $HOME/.config/tigervnc/passwd -display :0 -SecurityTypes=VncAuth; fi'

startsecs=0
autorestart=unexpected
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
priority=3
