[program:Chromium]
command=bash -c 'mkdir -p /data/google-chrome; touch "/data/google-chrome/First Run"; URL=$(jq --raw-output ".url // \"http://homeassistant:8123\"" /data/options.json); chromium --kiosk --no-sandbox --test-type --no-first-run --disable-dev-shm-usage --start-maximized --noerrdialogs --user-data-dir=/data/google-chrome "$URL"'
priority=5
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
